In [68]:
# multilinear Regression
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
import category_encoders as ce

In [69]:
data = pd.read_csv('Fish.csv')
ce_binary = ce.OrdinalEncoder(cols=['Species'])
data=ce_binary.fit_transform(data)

In [70]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0          1   242.0     23.2     25.4     30.0  11.5200  4.0200
1          1   290.0     24.0     26.3     31.2  12.4800  4.3056
2          1   340.0     23.9     26.5     31.1  12.3778  4.6961
3          1   363.0     26.3     29.0     33.5  12.7300  4.4555
4          1   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        7    12.2     11.5     12.2     13.4   2.0904  1.3936
155        7    13.4     11.7     12.4     13.5   2.4300  1.2690
156        7    12.2     12.1     13.0     13.8   2.2770  1.2558
157        7    19.7     13.2     14.3     15.2   2.8728  2.0672
158        7    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [71]:
y = np.array(data.iloc[:,1])
data = data.drop('Weight', 1)
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
      

In [72]:
data.insert(0,column='bias',value=1)
data

bias  Species  Length1  Length2  Length3   Height   Width
0       1        1     23.2     25.4     30.0  11.5200  4.0200
1       1        1     24.0     26.3     31.2  12.4800  4.3056
2       1        1     23.9     26.5     31.1  12.3778  4.6961
3       1        1     26.3     29.0     33.5  12.7300  4.4555
4       1        1     26.5     29.0     34.0  12.4440  5.1340
..    ...      ...      ...      ...      ...      ...     ...
154     1        7     11.5     12.2     13.4   2.0904  1.3936
155     1        7     11.7     12.4     13.5   2.4300  1.2690
156     1        7     12.1     13.0     13.8   2.2770  1.2558
157     1        7     13.2     14.3     15.2   2.8728  2.0672
158     1        7     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [73]:

X = np.array(data)

In [74]:
prod = X.T.dot(X)

In [75]:
prod = inv(prod)

In [76]:
prod = prod.dot(X.T)

In [77]:
b = prod.dot(y)

In [78]:
b

array([-767.22981028,   46.28472951,   29.36468946,  -44.04613019,
         31.68245855,   25.56025405,   56.17685323])

In [79]:
predy = X.dot(b)

In [80]:
predy

array([ 3.12302841e+02,  3.74753979e+02,  3.79164841e+02,  4.11048842e+02,
        4.63568771e+02,  4.81726468e+02,  5.09864492e+02,  4.64340352e+02,
        5.10268981e+02,  5.52876368e+02,  5.45785749e+02,  5.41102183e+02,
        4.96424915e+02,  5.58183996e+02,  5.84205617e+02,  6.19554124e+02,
        6.08410084e+02,  6.11792106e+02,  6.21805543e+02,  6.31638627e+02,
        6.51623673e+02,  6.55982769e+02,  6.35628308e+02,  6.97324467e+02,
        6.86397266e+02,  7.25265526e+02,  7.23747043e+02,  7.19339180e+02,
        7.54455396e+02,  8.38219431e+02,  8.23535296e+02,  8.20767609e+02,
        8.95988930e+02,  8.80995455e+02,  8.70591884e+02, -1.70237876e+02,
       -5.46885152e+01, -1.15036070e+01,  1.29149602e+01,  5.36206967e+01,
        5.64732329e+01,  5.03182214e+01,  6.22742950e+01,  9.71960482e+01,
        9.70530705e+01,  1.32231978e+02,  9.72293629e+01,  1.23015799e+02,
        1.84049211e+02,  1.67351228e+02,  2.09222311e+02,  1.92886518e+02,
        2.89529937e+02,  

In [81]:
plt.plot(indep,y)

NameError: name 'indep' is not defined

In [ ]:
plt.plot(indep,predy)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X,y)

In [ ]:
y_cap = model.predict(X)
y

In [62]:
y_cap

NameError: name 'y_cap' is not defined

In [ ]:
plt.plot(indep,y)

In [ ]:
plt.plot(indep,y_cap)

In [63]:
trainx, testx, trainy, testy = train_test_split(X,y, test_size=0.5, random_state=50)

In [64]:
model.fit(trainx, trainy)

NameError: name 'model' is not defined

In [ ]:
y_cap1 = model.predict(testx)

In [ ]:
plt.plot(trainx, trainy)

In [ ]:
plt.plot(testx, testy)

In [ ]:
np.linspace(1,4,5)

In [65]:
predy

array([ 3.12302841e+02,  3.74753979e+02,  3.79164841e+02,  4.11048842e+02,
        4.63568771e+02,  4.81726468e+02,  5.09864492e+02,  4.64340352e+02,
        5.10268981e+02,  5.52876368e+02,  5.45785749e+02,  5.41102183e+02,
        4.96424915e+02,  5.58183996e+02,  5.84205617e+02,  6.19554124e+02,
        6.08410084e+02,  6.11792106e+02,  6.21805543e+02,  6.31638627e+02,
        6.51623673e+02,  6.55982769e+02,  6.35628308e+02,  6.97324467e+02,
        6.86397266e+02,  7.25265526e+02,  7.23747043e+02,  7.19339180e+02,
        7.54455396e+02,  8.38219431e+02,  8.23535296e+02,  8.20767609e+02,
        8.95988930e+02,  8.80995455e+02,  8.70591884e+02, -1.70237876e+02,
       -5.46885152e+01, -1.15036070e+01,  1.29149602e+01,  5.36206967e+01,
        5.64732329e+01,  5.03182214e+01,  6.22742950e+01,  9.71960482e+01,
        9.70530705e+01,  1.32231978e+02,  9.72293629e+01,  1.23015799e+02,
        1.84049211e+02,  1.67351228e+02,  2.09222311e+02,  1.92886518e+02,
        2.89529937e+02,  

In [66]:
y

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        450. ,  500. ,  475. ,  500. ,  500. ,  340. ,  600. ,  600. ,
        700. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,  680. ,
        700. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  120. ,  150. ,  145. ,  160. ,  140. ,  160. ,
        169. ,  161. ,  200. ,  180. ,  290. ,  272. ,  390. ,  270. ,
        270. ,  306. ,  540. ,  800. , 1000. ,   55. ,   60. ,   90. ,
        120. ,  150. ,  140. ,  170. ,  145. ,  200. ,  273. ,  300. ,
          5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
      

NameError: name 'model' is not defined